name: Auto-Scailing-Instance-Deployment

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Config and Assets to S3
        run: |
          aws s3 cp ./default.conf s3://${{ secrets.S3_BUCKET_NAME }}/conf.d/default.conf
          aws s3 sync ./html/ s3://${{ secrets.S3_BUCKET_NAME }}/html/ --delete
#ecr에 docker 이미지 빌드 후 푸시
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
                       -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
  #aws ssh를 통해 ec2에 접속하여 nginx 설치 및 s3에서 파일 다운로드 후 nginx 재시작
      - name: Deploy to EC2 via SSM
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          aws ssm send-command \
            --targets "Key=tag:Namespace,Values=st1-cicd-ns" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/conf.d/default.conf /home/ec2-user/nginx/conf.d/default.conf",
              "aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/html/ /home/ec2-user/nginx/html/ --delete",
              "docker pull '"$ECR_REGISTRY/$ECR_REPOSITORY"':latest",
              "docker stop nginx-container || true",
              "docker rm nginx-container || true",
              "docker run -d --name nginx-container -p 80:80 -v /home/ec2-user/nginx/html:/usr/share/nginx/html -v /home/ec2-user/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf '"$ECR_REGISTRY/$ECR_REPOSITORY"':latest"
            ]' \
            --comment "Deploy Nginx container on EC2 using SSM" \
            --timeout-seconds 600 \
            --region ${{ secrets.AWS_REGION }}